# Conclusion {-}

This dissertation identified novel applications CSIA. In many studies, the physiological challenges of measuring stable isotope data (i.e., tissue turnover time) are often framed as a hindrance for data interpretation. In this dissertation I demonstrated that incorporating the physiological and biogeochemical conditions that influence stable isotope chemistry in consumers into study design can elucidate more information for a system of interest. For example, applying temporal lags based on tissue turnover times can identify delayed food web responses to ecological change. This research provides a detailed framework for incorporating stable isotope fractionation, tissue turnover time, beta values, and resource use into the study design and interpretation of CSIA data. Without consideration for each of these components of stable isotope chemistry, there will be errors in trophic position estimation and mixing model results that will hinder data interpretation and potentially result in misleading conclusions.  

Without accurate representation of the nitrogen fractionation that occurs when organic nitrogen is transformed to inorganic sources (mineralization, nitrification) contributions of salmon as a nutrient source to vegetation will be overestimated and is likely overestimated in previous marine derived nitrogen studies. The application of stable isotope mixing models requires accurate stable isotope end members to estimate dietary sources to consumers. When mixing models are applied to vegetation, consideration for the direct sources of nitrogen that plants “consume” are necessary (i.e., ammonium, nitrate, amino acids). My finding that soil ammonium is substantially enriched in $^{15}N$ compared to salmon tissue demonstrates salmon should not be used as an end member in mixing models applied to plants because it does not consider fractionation that occurs in soils. Understanding the contributions of salmon to the riparian environment also requires careful selection of a study site that has salmon present and a second control site without salmon. Control sites usually consider the composition of tree and vegetation community, but do not typically consider soil composition. I observed substantial site variability with distance from the same stream for sites previously used as controls. Slope, aspect, gravimetric water content, and soil type are just a few conditions that can alter nutrient content, fractionation in soil, and tree growth, and if not accounted for can lead to misinterpretations of marine derived nutrient studies. Conclusions from studies that do not confirm soil conditions are comparable between ‘salmon’ and ‘control’ sites should be interpreted with caution. Finally, marine derived nutrient studies should focus on measuring ecological responses to salmon presence rather than measuring the presence of marine derived nutrients from stable isotopes and assuming the presence of enriched nitrogen equates to increased nitrogen availability that will elicit an ecological response. My results found differences in marine derived nutrients with salmon presence but not increases in long-term nitrogen availability or transformation rates. Studies should focus on the ecological response (i.e., increased nitrogen transformation rates, increased tree growth) between ‘salmon’ and ‘control’ sites and apply stable isotopes to support the interpretation that ecological responses are due to salmon contributions.

I demonstrated source amino acids provide novel information about how nitrogen moves through and is utilized by food webs, particularly for retrospective analyses. Studies focused on understanding nitrogen resources directly measure phytoplankton blooms or nitrogen concentrations and datasets are only available for small areas and short periods of time. This presents a challenge of scale, both spatially and temporally, when trying to understand how these measurements contribute to mobile, large bodied, slow growing, marine consumers that integrate resources from over broader spatial ranges and longer time scales. The unique qualities of source amino acids that make them useful as an indicator of stable isotope baseline for consumers, also means they can serve as an important tracer on their own. Notably, source amino acids are still susceptible to the challenges in interpreting stable isotope values of nitrogen that occur from fractionation from nitrogen transformations, phytoplankton assimilation, and trophic enrichment. Therefore, the most interpretable and useful applications of source amino acid studies will trace long-term contributions of nitrogen sources with distinct stable isotope values. Sea ice derived algae is one example of a nitrogen sources that is enriched in 15N and measurable in consumer tissues based on our results. Measuring the nitrogen stable isotope values of source amino acids from historic and contemporary samples from environments where sea ice derived algae has been known to change due sea ice decline and oceanic warming such as Baffin Bay, could inform how food webs adapt their resource use in a changing world. 

Measuring trophic position in consumers such as harbor seals is useful for understanding general ecosystem change but identifying the specific mechanism that caused the trophic position change requires additional information. Some climate drivers were strong predictors of both source amino acid stable isotope values and trophic position estimates, but others were only good predictors of trophic position estimates. This is particularly relevant when trying to identify mechanisms of climate forcing on the food web. One approach for identifying whether the mechanisms of climate forcing is constraining nutrients at the base of the food web or is acting on recruitment and growth higher in the food web, is to combine analyses of both trophic position and source amino acids. For example, freshwater discharge impacts harbor seal trophic position and source amino acid stable isotope values. Therefore, climate variables are directly influencing nitrogen at the base of the food web which then is propagating through the food web and altering harbor seal trophic level. In contrast, sea surface temperature only impacted harbor seal trophic position, meaning it was altering abundance of mid trophic level species (likely forage fish) and that was the mechanism that was ultimately causing a trophic shift. Applying CSIA to mid trophic level species in addition to a top predator would provide a more complete picture of causal mechanisms of trophic level change of top predators. Specifically, it could identify if the trophic level change was occurring in the top predator (if the lower trophic level species did not also have a shift) or if it was occurring lower in the food web (if both species experienced a trophic level change).

Trophic position change can be difficult to interpret, particularly for high trophic level, generalist predators like harbor seals. Trophic position can change due to a dietary shift by the consumer of interest, a shift lower in the food web, or a shift in protein quality of prey. These mechanisms are more easily resolved when applying CSIA to specialist species compared to a generalist. One potential application would be the southern resident killer whale (SRKW) in Washington, that consumes exclusively salmon. Applying CSIA to SRKW would eliminate the potential of protein quality influencing data interpretation (due to the exclusively piscivorous diet) therefore a trophic level change in SRKW would indicate consumption of smaller salmon. This could be the result of eating a greater number of smaller species such as pink salmon, or smaller individuals of Chinook salmon. While the exact mechanism would still not be identified from CSIA data alone, it would identify a change in the SRKW – salmon relationship and if combined with pacific Salmon abundance and size data which are collected annually, it would offer a more complete picture of the dynamics of this relationship through time than abundance data alone. 

Ecological integrity indicators have been incorporated into the California Current Integrated Ecosystem Assessment and include indicators of trophic structure such as mean groundfish trophic level. Harbor seal trophic position could be a useful addition to these datasets. This dissertation provides a historic baseline which contemporary data can be compared to. In addition, contemporary mean groundfish trophic level is collected annually. Combined, these two datasets are a powerful tool for measuring ecological integrity. The addition of harbor seal data would determine whether changes in ecological integrity span the entire food web and identify whether observed changes are confined to certain parts of the food web. For example, if changes were observed in harbor seals but not groundfish that would indicate predators were modifying their foraging strategies. If a change was observed in both groundfish and harbor seals, then it would indicate a bottom-up effect propagating through the entire food web. Collection of harbor seal trophic position data for indicators would ideally occur annually, but data that is pooled over 1-5 years should be sufficient for identifying widescale ecological change, as this dissertation shows harbor seal trophic position response to food web and climate conditions are often delayed by multiple years. A continuous sampling strategy may be able to be incorporated into marine mammal stranding networks. Pooling data on decadal scales may be more feasible, but it comes with the risk of overlooking potential food web responses based on how the decadal breakpoints correspond temporally relative to the ecological change.  Alternatively, samples could be collected in the two years following major climate perturbations. Given the lagged response due to both tissue turnover and propagation of ecological conditions up the food web, and the increase in extreme climate events over the past two decades, it would be possible to retroactively analyze the effects of extreme climate conditions on the food web by measuring predator tissues in the 1-3 years following the event.  

Compound-specific stable isotope analysis can provide novel information regarding ecological and biogeochemical responses to climate change. An important component to the application and interpretation of this type of data is the physiological and biogeochemical parameters that influence stable isotope fractionation. With my dissertation as a foundation future work can better constrain assumptions of stable isotope parameters to reconstruct historic datasets and apply CSIA data to understand delayed food web responses and resource assimilation into food webs.   



