`r if(knitr:::is_latex_output()) '\\appendix'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

<!--
If you feel it necessary to include an appendix, it goes here.
-->

# Appendix 1
## Text 1: Full analytical details for stable isotopes

Collagen samples have been analyzed for both CSSIA and bulk $\delta^{15}N$ which require 10 mg of purified collagen (100 mg of bone). Preliminary analyses were conducted to determine the highest rate of collagen return from bone sampled from different parts of the skull to minimize destruction. Samples were taken from the internal occipital shelf to maintain external integrity. Bone was decalcified using 0.2 M HCl for 24-72 hours depending on bone thickness, followed by centrifugation and nanopure water rinse. Removal of humic acids was conducted using 0.125 M NaOH for 20 hours. Samples were washed to a neutral pH, then solubilized in 0.01N HCl. Once solubilized samples were blown down under N2 to prevent isotopic fractionation, and freeze dried. Freeze dried collagen was be analyzed for bulk isotopic composition of nitrogen by the UW IsoLab (isolab.ess.washington.edu) using a coupled elemental analyzer-isotope ratio mass spectrometer following the standard protocols of the laboratory. C:N ratios were calculated from this data, which is a measure of the quality for carbon and nitrogen analyses of bone collagen for isotopic analysis. Only three observations were outside of the acceptable rang of 2.7-3.6; indicating there was no substantial loss of glycine or addition of nitrogen due to microbial processing from mortality, decay, curation, and analysis. 
	
$\delta^{15}N$ of eleven amino acids  were measured in the UW Facility for Compound-Specific Isotope Analysis of Environmental Samples. Samples were prepared following the procedures developed by Popp Marine Lab at University of Hawaii Manoa. Briefly, proteins were hydrolyzed in 6N HCl and purified using a cation exchange column. Amino acids were esterified using isopropanol acetyl chloride, and derivatized via acylation with 4:1 toluene: pivaloyl chloride. Samples were brought up in ethyl acetate and analyzed using a coupled gas chromatography-combustion-isotope ratio mass spectrometer system (GC-C-irMA; Thermo Scientific Trace GC + GC IsoLink coupled to a Delta V irMS) in continuous flow mode monitoring masses (m/z) 28 and 29 using a db-35 column. For each run a 12 amino acid external standard with known isotopic composition was injected three times followed by sample injections. Samples were injected in triplicate, with the 12 amino acid standard injected every two samples (or six injections). A two-hour column oxidation was performed after 6 samples (25 injections). Samples and standards included norleucine as an internal standard.
	
For each machine run, a linear model was fit for each individual amino acid using the following equation:
	
\begin{equation} 
  Std_{aa} = m_{aa}t + b_{aa}
  (\#eq:std)
\end{equation} 

Where m represents the slope of the precision drift, *t* represents the injection number since last column oxidation, and *Std* represents the $\delta^{15}N$ of an individual amino acid for a standard observation. The data was then corrected using the following equations:

\begin{equation} 
  D_{aa, t} = Std_{aa,t} - True
  (\#eq:diff)
\end{equation} 

Where $D_{aa,t}$ is the difference between an observed standard $\delta^{15}N$ of $Std_{aa,t}$ for a given amino acid at a given injection number and the true $\delta^{15}N$ for that standard. Then:

\begin{equation} 
  Sample_{corrected,aa,t} = Sample_{obs,aa,t} - D_{aa,t}
  (\#eq:sampcorr)
\end{equation} 

Where the drift value, $D_{aa,t}$, is subtracted from the sample value for a given amino acid and a given injection to correct the observed sample values for precision drift since last column oxidation. Mean sample corrected values for the triplicate injections were used for all amino acid $\delta^{15}N$. 


## Text 2: Identifying size and sex-based trends in harbor seal trophic position

Only a subset of the samples included month of collection, sex, and length metadata and therefore separate month, length, and sex specific analyses were fit to the data to test whether they should be considered as predictors for the ocean condition and prey availability data. Standard linear models with: 1) sex as a factor, 2) length as a continuous covariate and 3) month as a continuous covariate were fit to both Salish Sea and coastal WA for each individual trophic amino acid. These models were used to test whether trophic position varies with length and sex, whether these trends are consistent between amino acids, and whether one year was an appropriate approximation for tissue turnover of bone collagen. The standard linear models took the following structure: 
	
\begin{equation} 
 y_i \sim N(\boldsymbol{\alpha}_{j[i]} + \boldsymbol{\beta}_{j[i]}\boldsymbol{x}_i, \sigma^2_y)
  (\#eq:hiermods2)
\end{equation}

where *y* represents harbor seal trophic position calculated from phenylalanine and a trophic amino acid *i*, $\boldsymbol{X}$ is a matrix of bottom-up drivers for a given model, $\boldsymbol{\beta}$ is a vector of covariates (sex, length, month, location), and *a* is the intercept. There were no significant differences in trophic position between male and female harbor seals in either the Salish Sea (Figure \@ref(fig:sexWA)A) or coastal Washington (Figure \@ref(fig:sexWA)B); this relationship was consistent across amino acids. Similarly, trophic position did not change based on harbor seal length (Figure \@ref(fig:lengthWA)). Interestingly, the exception to this finding was trophic position calculated by proline, which showed a significant decline with size. Mean harbor seal trophic position calculated from proline for harbor seals ranging from 150 - 180 cm in standard was 0.6 lower than harbors seals that were less than 120 cm of standard length (Figure \@ref(fig:lengthWA)). Trophic position calculated from alanine, aspartic acid and valine also showed negative trends with size, although the trend was not statistically significant, while trophic position calculated from glutamic acid was positive but also not statistically significant. There was also no observed ‘seasonality’ in harbor seal trophic position (Figure \@ref(fig:season)) indicating 1-year physiological delay was a reasonable approximation for tissue turnover time of skull bone collagen. 

Harbor seals in Washington do not have distinct trophic ecology based on adult size (Figure \@ref(fig:sexWA)) or sex (Figure \@ref(fig:lengthWA)). @Bjorkland2015 did not observe sex or size (weight) based differences in bulk $\delta^{15}N$ values in harbor seals in the San Juan Islands in the Salish Sea between 2007 and 2008. Our results agree with this finding and with similar studies of other Pacific pinniped species [@Drago2009; @Dehn2007]. While both male and female harbor seals have a similar trophic position, it is possible sex and size-based differences in foraging strategies within a similar trophic position exist [@Bjorkland2015; @Wilson2014]. Additionally, this study focused on adult harbor seals and changes in trophic position between juveniles, sub adults and adults are possible as indicated by pinniped studies [@Zhao2004]. Regardless, our results show long-term consistencies in the trophic niche exploited by both male and female harbor seals regardless of adult size in Washington.

## Text 3: Identifying temporal trends in harbor seal trophic position

To understand any changes through time to harbor seal foraging ecology over the past 100 years that were not explained by the tested environmental and food web covariates (Tables \@ref(tab:ocmod) & \@ref(tab:prmod)), generalized additive models (GAMs) were fit the residuals for the best ocean condition-prey model with a smooth term by year and a k term of 5. These analyses (Figures 3.6 & 3.7) were compared to the raw time series of harbor seal trophic position data (Figure \@ref(fig:year)) to identify trends through time that are unexplained by the covariates included in this analysis.

Trends in harbor seal trophic position through time were different between the Salish Sea and coastal Washington (Figure \@ref(fig:year)). The time series of the glutamic acid trophic position in coastal Washington had a significant positive trend through time (Figure \@ref(fig:year)b) that increased from 1948-1968 and remained relatively constant following 1975. Trophic position calculated from alanine and proline showed similar trends, although the alanine trophic position trend was not statistically significant (Figure \@ref(fig:year)a). In contrast, harbor seal trophic position in the Salish Sea calculated from glutamic acid, alanine, aspartic acid, and proline has been relatively stable over the past century, but the trophic position calculated from valine showed a significant decline since 1968. 

There were no trends through time for the model residuals for any amino acid after accounting for environmental (Figure 3.6) and food web (Figure 3.7) conditions at all three time lags. This indicates that prey availability and ocean conditions account for most temporal variation observed in the trophic position time series (Figure \@ref(fig:year)). However, valine was a notable exception, which demonstrated a decreasing trend through time in model residuals for all of the models with the most support. 


##Text 4: Accounting for variability in trophic enrichment factors 
Trophic enrichment factors are variable based on animal diet (omnivory, carnivory, herbivory), pathways of nitrogen excretion, and trophic level [@Nielsen2015; @McMahon2015] with ominvory, carnivory and higher trophic levels demonstrating the lowest trophic enrichment for most amino acids. Trophic enrichment has ultimately been attributed to diet quality (similarity in tissues between consumer and prey) and mode of nitrogen excretions, although the relative impacts of each is difficult to discern, especially considering most controlled feeding studies include low-trophic level ammonia excretion but not high trophic level species (i.e., adult hake or salmon). In coastal Washington, most trophic transfers are between high diet quality, piscivorous fish (ammonia excretion) with a high-quality transfer between fish and harbor seal (urea excretion). Studies using multiple trophic enrichment factors based on the food web structure and consumption type produce more accurate trophic position estimations especially for higher level consumers [@McMahon2015; @McMahon2016; @McMahon2019]. 

We applied multiple trophic position calculation frameworks for harbor seals to determine the best approach (Table \@ref(tab:tpparam)) by identifying the percentage of data that fell within an ecologically realistic trophic position range for harbor seals. We also applied these approaches to herring, a known harbor seal prey species, with data from @Germain2013. Based on known foraging patterns, we anticipate harbor seals have an average trophic position of 3.5 to 5 and herring will have an average trophic position of 2.5-2.9. Equation 2 from (Figure \@ref(fig:nvbeta).2) produced the most accurate herring trophic position estimates for most amino acids, however valine produced an impossibly low estimate of trophic position. In contrast, equation 3 (Figure \@ref(fig:nvbeta).3) produced the most accurate results for most amino acids compared to harbor seals, but these estimates were still unrealistically low for some amino acids (proline, valine), which is common for CSIA [@McMahon2016]. Additionally, this is not the most ecologically accurate parameterization, as it assumes all trophic transfers are of high prey quality, where there must be at least one herbivorous-low quality trophic transfer in the food web from phytoplankton to zooplankton (parameterization of equation 4, Figure \@ref(fig:nvbeta).4).  It also assumes prey quality (carnivorous) and trophic level of the consumer is more important than nitrogen excretion pathway (urea versus ammonia) for some amino acids but not others. Seemingly, these assumptions impact trophic position estimates from individual trophic amino acids differently which will likely be an important consideration for future studies applying a multi-amino acid framework. It is possible that these reflect biases in conventional trophic position estimates (i.e., stomach content analysis) as proposed by @McMahon2015 or there may be biases in controlled feeding studies. For example, growth rate of individuals in controlled feeding studies may not accurately reflect those in natural ecosystems which may lead to overestimates in trophic enrichment if they are higher in natural systems compared to controlled feeding experiments. This may be plausible in the Washington food web as consumption of juvenile fish is common at multiple trophic levels, and juveniles presumably have higher growth rates than adults. 

Mean harbor seal trophic position estimates were similar across trophic amino acids however some were more variable than others. The standard deviation of trophic position was higher for proline (4.6 ± 0.7, mean ± 1SD), and valine (3.7 ± 0.8) and included more ecologically unrealistic values compared to glutamic acid (4.5 ± 0.4) and alanine (3.9 ± 0.4). Trophic position calculated from aspartic acid (4.1 ± 1.0) had the highest standard deviation and also demonstrated a trend through time compared to other amino acid trophic position calculations (Figure \@ref(fig:year)). 

Application of a multi-amino acid trophic position calculation 1) offered a more realistic parameterization of the trophic position equation, 2) improved model certainty and 3) produced similar covariate coefficients compared to a glutamic acid only parameterization. Examination of the distribution of trophic position calculations for each individual trophic amino acid shows variability in accuracy and variance for single trophic amino acid calculations (Figures \@ref(fig:nbeta) & \@ref(fig:nvbeta)). For example, aspartic acid had a much wider variance compared to other amino acids (Figures \@ref(fig:nbeta) & \@ref(fig:nvbeta)) and also produced different trends through time (Figure \@ref(fig:year)). 

It is likely differences in tissue turnover time between individual amino acids and phenylalanine contribute to the variance of the trophic position estimates derived from individual trophic amino acids. @Downs2014 found phenylalanine takes 780 hours to reach 50\% turnover in shrimp. This is comparable to glutamic acid, alanine, and valine which take 940, 642, and 942 hours respectively which are substantially lower than aspartic acid which requires 1530 hours. The discrepancy between tissue turnover times between aspartic acid and phenylalanine is likely the cause of the broad distribution for aspartic acid derived trophic position compared to other trophic amino acids, as aspartic acid is incorporating the nitrogen isotope signature over a substantially larger time period relative to phenylalanine and thus may incorporate more prey switching and/or changes in the isotopic signature of primary producers. 

Addition of alanine to the glutamic acid only model resulted in the largest difference in model certainty. A glutamic acid – alanine model supported the same best models for both the environmental and prey models at all time lags. The combined tissue turnover of glutamic acid and alanine of shrimp (791 hours) is very similar to that of phenylalanine (780 hours) ensuring both the trophic and source amino acids were incorporated over a similar time scale (albeit the trophic amino acids were a wider time scale). Benefits of a multi-amino acid trophic position equation may not require four amino acids as previously suggested [@Nielsen2015] but rather carefully selected trophic amino acids to ensure the trophic amino acids are incorporated over a similar time scale as the source amino acids. If tissue turnover times are unable to be approximated, utilizing four trophic amino acids or two source amino acids as suggested by @Nielsen2015 would likely provide the same benefit as fewer, carefully selected amino acids based on tissue turnover times.
