---
# UW thesis fields
title: "Applied ecosystem chemistry: linking biogeochemical and physiological processes to ecological interactions"
author: "Megan L Feddern"
year: "2021"
program: "School of Aquatic and Fishery Sciences"
chair: "Gordon W. Holtgrieve"
chairtitle: "Assistant Professor"
signature1: "Eric J. Ward"
signature2: "Tim Essington"
signature3: "Sarah Converse"
signature4: "Cecilia Bitz"
abstract: |
  Physical environments are changing globally due to anthropogenic impacts which has the potential to alter ecological interactions. To understand how ecological interactions are changing, long-term datasets are necessary to document ecological baselines from the past that are comparable to current ecological conditions. Stable isotope values can be useful chemical tracers for retrospective analyses which can elucidate changes in biogeochemistry and trophic interactions that influence food webs. My dissertation applies compound-specific stable isotope analysis (CSIA) of amino acids and inorganic nitrogen to understand long-term, regional, ecological responses to physical conditions in the northeast Pacific. I tested the long-term importance of salmon subsidies to Alaskan riparian ecosystems by measuring inorganic nitrogen concentrations, transformation rates, and nitrogen stable isotope values in soil following a 20-year carcass manipulation experiment. Carcass subsidies did not increase soil nitrogen concentrations or transformation rates but the nitrogen stable isotope value of ammonium was significantly enriched in 15N compared to salmon carcasses, indicating the importance of salmon derived nutrients is likely overestimated for some systems. Using museum skull specimens from two species of pinnipeds in the northeast Pacific, harbor seals (*Phoca vitulina*) and Steller sea lions (*Eumetopias jubatus*), I derived a century of predator stable isotope data. I compared the carbon and nitrogen stable isotope values of source amino acids to regional climate datasets and determined coastal food webs responded to climate regimes, coastal upwelling, and freshwater discharge, yet the strength of responses to individual drivers varied across the northeast Pacific. These findings demonstrate stable isotope data can serve as a tracer of nitrogen resources and phytoplankton dynamics that is specific to resources that are assimilated by food webs. To calculate pinniped trophic position from the historic dataset, I was the first to apply taxa-specific trophic enrichment factors, a system specific beta-value, a temporal lag to account for tissue turnover time, and a multi-trophic amino acid analysis framework within a single study. This approach constrained assumptions regarding physiological processes and vascular plant contributions to the food web, which can confound stable isotope data interpretation. I analyzed long-term predictors of harbor seal trophic position in Washington and identified delayed responses of harbor seals to both physical ocean conditions (upwelling, sea surface, discharge) and prey availability (Pacific hake, Pacific herring and Chinook salmon). Consideration for dynamic responses of harbor seals to their environment is an important factor for understanding predator-prey interactions as harbor seals respond to multiple ecological factors that are often changing simultaneously and their response occurs at multiple temporal scales. I then analyzed regional and decadal trends in pinniped trophic position in Alaska and identified the largest change in trophic position occurred in recent decades (2000 and 2010) but the direction of the trends diverged based on region and species. Gulf of Alaska pinnipeds are experiencing unique food web conditions in recent decades compared to the past likely in response to climate-induced ecological change in the region. Finally, I constructed a compartment model to explore the effect of stable isotope heterogeneity and consumer isotope incorporation rates on consumer trophic position estimates using both bulk stable isotope analysis and CSIA. Bulk stable isotope analysis produced consistent errors in trophic position estimates by as much as one trophic level that were more pronounced in higher trophic level consumers and CSIA was more accurate than bulk stable isotope analysis. Altogether, these results show CSIA is a useful tracer for elucidating long-term physical forcing mechanisms on food webs and incorporating physiological processes that govern stable isotope fractionation into sampling and analysis design can uncover forcing mechanisms that would otherwise be overlooked. 
acknowledgments: |
  My dissertation research was funded by several grants, Washington Sea Grant, University of Washington, pursuant to National Oceanic and Atmospheric Administration (award nos. NA18OAR4170095 and NA19OAR4170360), and the Joint Institute for the Study of the Atmosphere and Ocean (JISAO) under NOAA Cooperative Agreement NA15OAR4320063 (contribution no. 2020-1116). I personally was funded by the National Marine Fisheries Service -Sea Grant Joint Fellowship Program in Population and Ecosystem Dynamics, the School of Aquatic and Fishery Sciences Departmental Fellowships, incuding the H. Mason Keeler Endowment for Excellence and the Clairmont L. and Evelyn S. Egvedt Fellowship, the American Fisheries Society WA/BC Chapter Jeff Cederholm Scholarship, and Teaching Assistantship positions.

  I extend my deepest gratitude to my museum collaborators for permitting sampling and coordinating logistics. Specifically, I would like to thank Jeff Bradley and Sharlene Santana of the UW Burke Museum, Peter Wimberger and Gary Shugart of the Slater Museum, Link Olson and Aren Gunderson of the Museum of the North, Robert Delong of the National Marine Mammal Laboratory, Lesley Kennes and Gavin Hanke of the Royal BC Museum, and Darrin Lunde and John Ososky of the Smithsonian Institute. I thank Megan Stachura and Tom Royer for assistance with environmental datasets, and Chris Harvey and Jens Nielsen for helpful discussions and support. Hyejoo Ro and Karrin Leazer assisted in laboratory work. Mark Haught and Terry Rolfe assisted with GC/C/IRMS method development, maintenance, and troubleshooting.

  I thank the Alaska Salmon Program at the University of Washington for facilitating access to the field siteon Hansen Creek, specifically Jackie Carter, Katie McElroy, and Max Ramos for help with field sampling and logistics. The daily surveys and carcass manipulation (by 3– 5 people) have involved far more individuals than I can name, but I specifically thank Gregory Buck, Harry Rich, Jr., Curry Cunningham, Chris Boatright, Jackie Carter, and the undergraduate students in the Aquatic Ecological Research in Alaska classes.

  I am eternally grateful for the community that has supported me over the past five years. Thank you to my advisor, Gordon Holtgrieve, who encouraged my eclectic research interests and always supported me in finding work-life balance. My other committee members — Drs. Eric Ward, Sarah Converse, Tim Essington, and Cecilia Bitz — challenged me to think about my work broadly, communicate clearly, and think critically about my analyses. Although they were not officially part of my committee, Drs. Jens Nielsen at the Alaska Fisheries Science Center, NOAA and Steve Perakis at the Forest and Rangeland Science Center, USGS, taught me so much about chemistry, collaboration, and mentoring. Thank you to to all past and present members of the Holtgrieve Lab for bringing joy and commiseration to the trials and tribulations of lab work. My fellow SAFS graduate students have been an important part of my community, thank you for your support and friendship.
  
  And most importantly, thank you to my family and my parents.
dedication: |
  To my grandmother, Gail Feddern, who has read every publication I have ever written
# End of UW thesis fields
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  huskydown::thesis_pdf: 
    latex_engine: xelatex
    extra_dependencies: ["flafter"]
#  huskydown::thesis_gitbook: default
#  huskydown::thesis_word: default
#  huskydown::thesis_epub: default
bibliography: bib/thesis.bib
link-citations: yes
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
# space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the huskydown package is
# installed and loaded. This huskydown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(huskydown))
  devtools::install_github("benmarwick/huskydown")
library(huskydown)
```

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers on chapters. -->

# Introduction {.unnumbered}

Anthropogenic climate change will impact nutrient cycles, primary productivity, and thus ecosystem structure in the world’s oceans, although considerable uncertainty still exists regarding the variability of these changes and how ecosystems will respond. Changes in primary production has implications for dependent marine ecosystems, as it influences abundance and interactions in both adjacent and non-adjacent trophic levels [@Ware2005; @Winder2012; @Frank2015]. This bottom-up control of marine food webs is expected to reduce fishery yields by as much as 20% globally by 2100 due to productivity constraints at lower trophic levels [@Moore2018]. Given both resource availability and community composition of resources impact the function and stability of food webs [@Narwani2012] it is likely ecosystem interactions will change in response to environmentally induced shifts in resources in the future. 

Ecological interactions are a fundamental component to studying the function and dynamics of ecosystems. Currently, anthropogenic and climatic changes are altering ecological interactions at a global scale, thus, understanding how interactions function and how environmental perturbations will alter interactions is imperative. Studies of environmental control of food webs are often limited to only examining low trophic level species [@Pershing2010], or only include indices of either primary production or environmental change [@Ware2005; @Chassot2007]. Oceanic conditions such as sea surface temperature, freshwater discharge, wind, and ice cover, have been linked to abundance and recruitment of many fish species in the Northeast Pacific [@Cunningham2018; @Puerta2019; @Stachura2014], but studies rarely include proxies or indicators of either nutrient availability or primary productivity that enable mechanistic understanding of ecosystem response to the environment.

Lower trophic levels are sensitive to environmental variation in bottom-up drivers of productivity [@Ware2005; @Frank2006; @Jennings2010], but few studies have demonstrated how the impact of these changes span entire food webs on long time scales. Additionally, somatic growth of large bodied marine predators is not continuous and typically occurs on a longer temporal scale than phytoplankton dynamics making it challenging to link higher trophic level species to forcing lower in the food web. Similarly, marine predators can utilize resources at multiple spatiotemporal scales, creating a challenge for linking species abundance to independent observations of phytoplankton or nutrient dynamics. How environmentally induced changes in primary productivity ultimately influences nutrients available to and assimilated by the food web is thus poorly understood.

An empirical understanding of food web responses to environmental drivers requires long time series data that span multiple changes in climate regimes to decouple natural oscillations with long-term changes [@Litzow2007; @Tallis2010; @Hastings2018]. In recent decades extreme changes in marine environments have become more common and these events have had substantial impacts on ecosystems. Marine ecosystems in Alaska are experiencing unprecedented environmental change that has altered abundance and size distributions of many fish species [@Barbeaux2020; @Holsman2019; @Oke2020; @Suryan2021]. More recently, atmospheric circulation anomalies in the northeast Pacific Ocean have resulted in abnormally warm sea surface temperatures during the past decade [@Walsh2018] and this environmental shift has altered fish abundances [@Bond2015; @Litzow2020]. For example, the unprecedented marine heatwave that occurred in 2014 - 2016 triggered dramatic ecosystem change, including a 71% decline in Pacific cod in the Gulf of Alaska [@Barbeaux2020] and declines in phytoplankton biomass, forage fish abundance, and changes in community structure [@Suryan2021].

Reconstructing time series of indicators of ecosystem interactions is important to understand how ecosystems have responded to environmental variability in the past and ultimately interpret potential food web responses to environmental conditions in the future; such datasets are distinctly lacking. Modern chemical analyses, such as compound-specific stable isotope analysis (CSIA) of inorganic nitrogen sources or amino acids, have potential to improve our understanding of food web interactions by 1) extending time series through retrospective analyses 2) identifying environmental forcing of the entire food web when measured in predators and 3) informing biologically relevant mechanisms of interactions, a former limitation of many ecosystem studies. 

Analyses of nitrogen stable isotopes usually applies bulk stable isotope techniques which measures the $^{15}N/^{14}N$ ratio of nitrogen as a weighted average of all nitrogen present in a given sample. For tissue samples, $^{15}N/^{14}N$ measurements are a weighted average of the concentrations of all amino acids present in the protein of an individual tissue. For soil analyses, typically  $^{15}N/^{14}N$ includes both organic and inorganic form. However, the $^{15}N/^{14}N$ of an individual compound, known as compound-specific stable isotope analysis, represents the kinetic and diffusive fractionation factors exerted on that compound through chemical conversions, typically from biogeochemical or physiological processes. Thus, nitrogen isotope values can provide a useful link between biogeochemical reactions that regulate nutrient availability and primary production, and ecological responses, without being confounded by nitrogen containing compounds that are not utilized by an ecosystem. 

Here I aim to reconstruct historical food web interactions using stable isotopes as chemical tracers to:

1.	Identify how long-term (20-years) changes in salmon abundance impact nitrogen dynamics in riparian soils.

2.	Understand the how ocean conditions alter food web-assimilated nitrogen resources and primary production in the northeast Pacific.

3.	Identify dominant historical drivers of predator trophic position in the northeast Pacific, using trophic position as an indicator of major changes in food web dynamics and ecological interactions.

4.	Establish a framework to improve trophic position estimation of bulk and compound-specific stable isotope analysis for historical and contemporary studies. 
